my_robo:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  left_front_steering_controller:
    type: position_controllers/JointPositionController
    joint: left_front_steering_joint
    pid: {p: 0.1, i: 0.1, d: 0.1}

  left_rear_steering_controller:
    type: position_controllers/JointPositionController
    joint: left_rear_steering_joint
    pid: {p: 0.1, i: 0.1, d: 0.1}

  right_front_steering_controller:
    type: position_controllers/JointPositionController
    joint: right_front_steering_joint
    pid: {p: 0.1, i: 0.1, d: 0.1}

  right_rear_steering_controller:
    type: position_controllers/JointPositionController
    joint: right_rear_steering_joint
    pid: {p: 0.1, i: 0.1, d: 0.1}


  left_front_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_front_wheel_joint
    pid: {p: 0.1, i: 0.00, d: 0.00}

  left_rear_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_rear_wheel_joint
    pid: {p: 0.1, i: 0.00, d: 0.00}

  right_front_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: right_front_wheel_joint
    pid: {p: 0.1, i: 0.00, d: 0.00}

  right_rear_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: right_rear_wheel_joint
    pid: {p: 0.1, i: 0.00, d: 0.00}
